/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721Mock__factory } from "./ERC721Mock__factory";
export { MyToken__factory } from "./MyToken__factory";
