/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  AssetAuctionStorageUpgradeable,
  AssetAuctionStorageUpgradeableInterface,
} from "../../../../lib/modules/assetAuction/AssetAuctionStorageUpgradeable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "lastBidderForOrder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608080604052346014576090908161001a8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c6357bf500d14602857600080fd5b3460565760203660031901126056576004358252600160209081526040909220546001600160a01b03168152f35b5080fdfea264697066735822122097c9c51968ef488af562f7fae4e6ddb73109b2a4bfeab379bd69a0b939b2cdab64736f6c634300080f0033";

type AssetAuctionStorageUpgradeableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AssetAuctionStorageUpgradeableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AssetAuctionStorageUpgradeable__factory extends ContractFactory {
  constructor(...args: AssetAuctionStorageUpgradeableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AssetAuctionStorageUpgradeable> {
    return super.deploy(
      overrides || {}
    ) as Promise<AssetAuctionStorageUpgradeable>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AssetAuctionStorageUpgradeable {
    return super.attach(address) as AssetAuctionStorageUpgradeable;
  }
  override connect(signer: Signer): AssetAuctionStorageUpgradeable__factory {
    return super.connect(signer) as AssetAuctionStorageUpgradeable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AssetAuctionStorageUpgradeableInterface {
    return new utils.Interface(_abi) as AssetAuctionStorageUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AssetAuctionStorageUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AssetAuctionStorageUpgradeable;
  }
}
