/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProtocolTreasury,
  IProtocolTreasuryInterface,
} from "../../../interfaces/treasuryInterfaces/IProtocolTreasury";

const _abi = [
  {
    stateMutability: "payable",
    type: "receive",
  },
];

export class IProtocolTreasury__factory {
  static readonly abi = _abi;
  static createInterface(): IProtocolTreasuryInterface {
    return new utils.Interface(_abi) as IProtocolTreasuryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProtocolTreasury {
    return new Contract(address, _abi, signerOrProvider) as IProtocolTreasury;
  }
}
