/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155MockSol from "./ERC1155Mock.sol";
export type { erc1155MockSol };
import type * as erc721MockSol from "./ERC721Mock.sol";
export type { erc721MockSol };
import type * as tokens from "./tokens";
export type { tokens };
export type { ERC20Mock } from "./ERC20Mock";
