/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokens from "./tokens";
export type { tokens };
export type { ERC1155Mock } from "./ERC1155Mock";
export type { ERC20Mock } from "./ERC20Mock";
export type { ERC721Mock } from "./ERC721Mock";
