/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IPaymentsResolverInterface extends utils.Interface {
  functions: {
    "dutchAuctionFeeResolver(uint256)": FunctionFragment;
    "englishAuctionFeeResolver(uint256)": FunctionFragment;
    "sellFeeResolver(uint256)": FunctionFragment;
    "swapFeeResolver()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "dutchAuctionFeeResolver"
      | "englishAuctionFeeResolver"
      | "sellFeeResolver"
      | "swapFeeResolver"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "dutchAuctionFeeResolver",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "englishAuctionFeeResolver",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "sellFeeResolver",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapFeeResolver",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "dutchAuctionFeeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "englishAuctionFeeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellFeeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapFeeResolver",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPaymentsResolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPaymentsResolverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    dutchAuctionFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { makerEarnings: BigNumber }>;

    englishAuctionFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { makerEarnings: BigNumber }>;

    sellFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { makerEarnings: BigNumber }>;

    swapFeeResolver(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { feeToBePaid: BigNumber }>;
  };

  dutchAuctionFeeResolver(
    value: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  englishAuctionFeeResolver(
    value: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sellFeeResolver(
    value: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  swapFeeResolver(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    dutchAuctionFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    englishAuctionFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapFeeResolver(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    dutchAuctionFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    englishAuctionFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapFeeResolver(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    dutchAuctionFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    englishAuctionFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sellFeeResolver(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapFeeResolver(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
