/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PaymentsResolverOperationsUpgradeable } from "./PaymentsResolverOperationsUpgradeable";
export type { PaymentsResolverOperationsV1 } from "./PaymentsResolverOperationsV1";
