/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVestingEscrow,
  IVestingEscrowInterface,
} from "../../../interfaces/vestingEscrowInterfaces/IVestingEscrow";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "vestee",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "cliffDays",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "initiallyAvailableTokens",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "periodMonths",
        type: "uint256",
      },
    ],
    name: "vest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IVestingEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): IVestingEscrowInterface {
    return new utils.Interface(_abi) as IVestingEscrowInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVestingEscrow {
    return new Contract(address, _abi, signerOrProvider) as IVestingEscrow;
  }
}
