/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AssetAuctionEventsUpgradeable } from "./AssetAuctionEventsUpgradeable";
export type { AssetAuctionOperationsUpgradeable } from "./AssetAuctionOperationsUpgradeable";
export type { AssetAuctionStorageUpgradeable } from "./AssetAuctionStorageUpgradeable";
export type { AssetAuctionV1 } from "./AssetAuctionV1";
